FROM node:10.16.0
MAINTAINER gmae199boy
WORKDIR /home/dev/xestate_react
COPY . /home/dev/xestate_react
# EXPOSE 9000
# WORKDIR /home/kim/project
RUN npm install -g nodemon
RUN npm install
CMD ["npm", "start"]